trigger:
  branches:
    include:
    - '*'

#Setup the variables used by the build, publish and deployment
variables:
  pool: 'K8S-Common-Pipeline' 
  containerRegistry: winacr02.azurecr.io
  dockerSvcConn: winacr02
  dockerRepo: k8s-common/demo
  javaVersion: "17"
  dockerOnly: false
  buildStdConfigMap: true

#Reference and invoke the templated build.
resources:
  repositories:
    - repository: templates
      type: git
      name: Process/k8s-common-build-templates

stages:
- stage: BuildAndDeployDev
  variables:
    env: dev
  displayName: 'Java build and deploy ${{variables.env}}'
  jobs:
  - job: Maven_Build
    displayName: 'Maven Build'
    pool:
      name: ${{variables.pool}}
      demands:
      - maven
      # - docker
      - JAVA_HOME_${{variables.javaVersion}}_X64
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m -Dspring-boot.build-image.imageName=${{variables.containerRegistry}}/${{variables.dockerRepo}}:latest'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.17'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        goals: '-Pnative spring-boot:build-image'

- stage: Push Docker Image
  variables:
    env: dev
    # host: ms-dev.windstream.com
    # clusterName: aks08-dev-scus
    # adoEnv: '${{variables.clusterName}}-${{variables.namespaceRoot}}-${{variables.env}}.${{variables.namespaceRoot}}-${{variables.env}}'
  displayName: 'Build and deploy ${{variables.env}}'
  jobs:
  - job: Push${{variables.env}}
    displayName: 'Push Image ${{variables.env}}'
    pool:
      name: ${{variables.pool}}
      demands:
      - docker
    steps:
    - template: istio-build-steps.yaml@templates
      parameters:
        command: 'push'
        serviceName: ${{variables.serviceName}}
        dockerRepo: ${{variables.dockerRepo}}
        dockerTag: 'latest'
        dockerSvcConn: ${{variables.dockerSvcConn}}
        # dockerOnly: ${{variables.dockerOnly}}
        # buildStdConfigMap: ${{variables.buildStdConfigMap}}
