create table matches (id bigint generated by default as identity, person_fk bigint not null, pet_fk bigint not null, primary key (id))
create table person (id bigint generated by default as identity, address1 varchar(255) not null, address2 varchar(255), city varchar(255) not null, dob timestamp, email varchar(255) not null, first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, role varchar(255), state varchar(255) not null, username varchar(255) not null, zip integer not null, shelter_id bigint, primary key (id))
create table pet (id bigint generated by default as identity, chip_id varchar(255), dob timestamp, name varchar(255) not null, shelter_fk bigint not null, primary key (id))
create table pet_image (id bigint generated by default as identity, image_name varchar(255), pet_fk bigint not null, primary key (id))
create table shelter (id bigint generated by default as identity, address1 varchar(255) not null, address2 varchar(255), approved boolean, city varchar(255) not null, name varchar(255) not null, requestor_user_name varchar(255), state varchar(255) not null, zip integer not null, primary key (id))
alter table person add constraint ID_PERSON_USERNAME_IDX unique (username)
create index ID_PET_NAME_IDX on pet (name)
create index ID_SHELTER_FK_ID_IDX on pet (shelter_fk)
alter table pet add constraint ID_CHIP_ID_IDX unique (chip_id)
alter table shelter add constraint ID_SHELTER_NAME_IDX unique (name)
alter table matches add constraint FK87dvnri5dp9nksubo1fq0kk21 foreign key (person_fk) references person
alter table matches add constraint FKqwfbbhph0r7j6dr979ga2wxeq foreign key (pet_fk) references pet
alter table person add constraint FKrpao463pcgdwwbo2084qjfa5t foreign key (shelter_id) references shelter
alter table pet add constraint FK4l4wyuu37apym335r8tshgl8x foreign key (shelter_fk) references shelter
alter table pet_image add constraint FKd9e687veildsdestee0t1wlov foreign key (pet_fk) references pet
