version: '2'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8.0-3
    environment:
      PMA_ARBITRARY: '1'
    ports:
     - 80:80/tcp
    stdin_open: true
    tty: true
  mysql:
    image: mysql:5.6.33
    environment:
      MYSQL_ROOT_PASSWORD: password
    stdin_open: true
    ports:
      - 3306:3306/tcp
    tty: true
    volumes:
      - mysql-demo-volume:/var/lib/mysql

volumes:
  mysql-demo-volume:
    external: true