version: '2'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8.0-3
    environment:
      PMA_ARBITRARY: '1'
    ports:
     - 80:80/tcp
    stdin_open: true
    tty: true
  mysql:
    image: mysql:5.6.33
    environment:
      MYSQL_ROOT_PASSWORD: password
    stdin_open: true
    ports:
      - 3306:3306/tcp
    tty: true
    volumes:
      - mysql-demo-volume:/var/lib/mysql
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.2
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  mysql-demo-volume:
    external: true
  zookeeper_data:
    external: true
  kafka_data:
    external: true